-- AlterTable
ALTER TABLE `delivery_schedule_entries` MODIFY `status` ENUM('PENDING', 'DELIVERED', 'NOT_DELIVERED', 'CANCELLED', 'SKIPPED', 'SKIP_BY_CUSTOMER', 'INDRAAI_DELIVERY', 'DELIVER_TO_AGENT') NOT NULL DEFAULT 'PENDING';
